# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revoco < Formula
  desc "Data liberation tool for escaping big tech walled gardens"
  homepage "https://github.com/fulgidus/revoco"
  version "0.1.9"
  license "GPL-3.0"

  depends_on "exiftool"
  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fulgidus/revoco/releases/download/v0.1.9/revoco_0.1.9_darwin_amd64.tar.gz"
      sha256 "39d7964cbc6b954b632676214ce9ce4b285b0eb1f833e93208dd82c824ea0814"

      define_method(:install) do
        bin.install "revoco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fulgidus/revoco/releases/download/v0.1.9/revoco_0.1.9_darwin_arm64.tar.gz"
      sha256 "cd984f0712e27e0b5b0701cc5ac4f86b5921c3671e89de585b194673d6f08905"

      define_method(:install) do
        bin.install "revoco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fulgidus/revoco/releases/download/v0.1.9/revoco_0.1.9_linux_amd64.tar.gz"
      sha256 "5c0c0af9a042f7578b47adc2620c0d161fcfba5213be4a577c7f3bc0e2db6a48"
      define_method(:install) do
        bin.install "revoco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fulgidus/revoco/releases/download/v0.1.9/revoco_0.1.9_linux_arm64.tar.gz"
      sha256 "f740f113d59473fb10574acf07fce8f34070fc4619c016c3be47b88e5720cd9e"
      define_method(:install) do
        bin.install "revoco"
      end
    end
  end
end
